[tool.poetry]
name = "AirPyllution"
version = "0.1.0"
description = "A package which  provides various functionalities on air pollution data."
authors = ["Christopher Alexander, Daniel King, Mel Liow"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
